import { TemplateConfig } from '../types/theme';

export const TEMPLATES: Record<string, TemplateConfig> = {
  minimal: {
    id: 'minimal',
    name: 'Minimal Clean',
    layout: 'stacked',
    buttonStyle: 'rounded',
    fontStyle: 'modern',
    background: '#ffffff',
    textColor: '#1a1a1a',
    accentColor: '#000000',
    cardBg: '#f3f4f6',
  },
  neon: {
    id: 'neon',
    name: 'Dark Neon',
    layout: 'stacked',
    buttonStyle: 'hard-shadow',
    fontStyle: 'mono',
    background: '#0f172a',
    textColor: '#ffffff',
    accentColor: '#22d3ee',
    cardBg: '#1e293b',
    cardBorder: '1px solid #22d3ee',
    cardShadow: '0 0 10px #22d3ee',
  },
  gradient: {
    id: 'gradient',
    name: 'Soft Gradient',
    layout: 'stacked',
    buttonStyle: 'pill',
    fontStyle: 'modern',
    background: 'linear-gradient(135deg, #fdfbfb 0%, #ebedee 100%)',
    textColor: '#4a5568',
    accentColor: '#ec4899',
    cardBg: 'rgba(255, 255, 255, 0.8)',
    cardShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
  },
  glass: {
    id: 'glass',
    name: 'Glass Card',
    layout: 'stacked',
    buttonStyle: 'rounded',
    fontStyle: 'modern',
    background: 'linear-gradient(to right, #4facfe 0%, #00f2fe 100%)',
    textColor: '#ffffff',
    accentColor: '#ffffff',
    cardBg: 'rgba(255, 255, 255, 0.2)',
    cardBorder: '1px solid rgba(255, 255, 255, 0.3)',
    cardShadow: '0 8px 32px 0 rgba(31, 38, 135, 0.37)',
  },
  bold: {
    id: 'bold',
    name: 'Bold Creator',
    layout: 'grid',
    buttonStyle: 'square',
    fontStyle: 'serif',
    background: '#fbbf24',
    textColor: '#000000',
    accentColor: '#000000',
    cardBg: '#ffffff',
    cardBorder: '2px solid #000000',
    cardShadow: '4px 4px 0px #000000',
  },
};
