import { TemplateConfig } from '../types/theme';

export const TEMPLATES: Record<string, TemplateConfig> = {
  comic_bio: {
    id: 'comic_bio',
    name: 'Comic Bio',
    layout: 'stacked',
    buttonStyle: 'hard-shadow',
    fontStyle: 'comic',
    background: '#ffe9c7',
    textColor: '#000000',
    accentColor: '#ffd93d',
    cardBg: '#ffffff',
    cardBorder: '4px solid #000000',
    cardShadow: '10px 10px 0 #000000',
  },
  sunset_motion_profile: {
    id: 'sunset_motion_profile',
    name: 'Sunset Motion Profile',
    layout: 'stacked',
    buttonStyle: 'rounded',
    fontStyle: 'modern',
    background: 'linear-gradient(180deg, #F6B37A 0%, #E47A2E 50%, #C7A6B8 100%)',
    bgSize: '100% 200%',
    animation: 'gradient-y 15s ease infinite',
    textColor: '#FFFFFF',
    accentColor: '#2C2C2C',
    cardBg: '#FFFFFF',
    cardBorder: 'none',
    cardShadow: '0 8px 24px rgba(0, 0, 0, 0.08)',
  },
  brush_artist_card: {
    id: 'brush_artist_card',
    name: 'Brush Artist Card',
    layout: 'stacked',
    buttonStyle: 'rounded',
    fontStyle: 'modern',
    background: '#F4F4F4',
    textColor: '#1A1A1A',
    accentColor: '#9C948A',
    cardBg: 'transparent',
  },
  yellow_hero_card: {
    id: 'yellow_hero_card',
    name: 'Yellow Hero Card',
    layout: 'stacked',
    buttonStyle: 'pill',
    fontStyle: 'modern',
    background: '#FFD600',
    textColor: '#222222',
    accentColor: '#8C7A00',
    cardBg: '#F2F2F2',
  },
  aurora_motion: {
    id: 'aurora_motion',
    name: 'Aurora Motion',
    layout: 'stacked',
    buttonStyle: 'rounded',
    fontStyle: 'modern',
    background: 'radial-gradient(circle at 50% 50%, #4c1d95 0%, #5b21b6 25%, #0e7490 50%, #0f172a 100%)',
    bgSize: '200% 200%',
    animation: 'gradient-xy 15s ease infinite',
    textColor: '#ffffff',
    accentColor: '#22d3ee',
    cardBg: 'rgba(255, 255, 255, 0.05)',
    cardBorder: '1px solid rgba(255, 255, 255, 0.1)',
    cardShadow: 'inset 0 0 20px rgba(255, 255, 255, 0.05)',
    cardBackdropBlur: 'blur(12px)',
    avatarAnimation: 'float 6s ease-in-out infinite',
    containerGlass: true,
    blobAnimation: true,
    textOpacity: 0.9,
  },
  neon_pulse: {
    id: 'neon_pulse',
    name: 'Neon Pulse',
    layout: 'stacked',
    buttonStyle: 'rounded',
    fontStyle: 'modern',
    background: '#09090B',
    textColor: '#FFFFFF',
    accentColor: '#00FFFF',
    cardBg: '#09090B',
    cardBorder: '1px solid #00FFFF',
    cardShadow: '0 0 5px rgba(0, 255, 255, 0.5), inset 0 0 10px rgba(0, 255, 255, 0.1)',
    gridAnimation: true,
    avatarAnimation: 'pulse-ring 3s infinite',
  },
  liquid_glass: {
    id: 'liquid_glass',
    name: 'Liquid Glass',
    layout: 'stacked',
    buttonStyle: 'rounded',
    fontStyle: 'modern',
    background: 'radial-gradient(circle at 50% 0%, rgba(219, 234, 254, 0.8) 0%, rgba(239, 246, 255, 0) 50%), radial-gradient(circle at 0% 100%, rgba(224, 242, 254, 0.8) 0%, rgba(239, 246, 255, 0) 50%), linear-gradient(180deg, #f0f9ff 0%, #e0f2fe 100%)',
    textColor: '#1e293b',
    accentColor: '#3b82f6',
    cardBg: 'rgba(255, 255, 255, 0.4)',
    cardBorder: '1px solid rgba(255, 255, 255, 0.4)',
    cardShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.02), 0 2px 4px -1px rgba(0, 0, 0, 0.02)',
    cardBackdropBlur: 'blur(12px)',
    avatarAnimation: 'float 6s ease-in-out infinite',
    containerGlass: true,
    textOpacity: 0.8,
  },
  motion_stack: {
    id: 'motion_stack',
    name: 'Motion Stack',
    layout: 'stacked',
    buttonStyle: 'rounded',
    fontStyle: 'modern',
    background: 'linear-gradient(135deg, #0f172a 0%, #1e293b 100%)',
    textColor: '#f8fafc',
    accentColor: '#38bdf8',
    cardBg: '#1e293b',
    cardBorder: '1px solid rgba(148, 163, 184, 0.1)',
    cardShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
    textOpacity: 0.95,
    avatarAnimation: 'fade-scale 0.8s ease-out',
  },
  premium_dark: {
    id: 'premium_dark',
    name: 'Premium Dark',
    layout: 'stacked',
    buttonStyle: 'rounded',
    fontStyle: 'modern',
    background: '#0E0E10',
    textColor: '#FFFFFF',
    accentColor: '#FFFFFF',
    cardBg: '#18181B',
    cardBorder: '1px solid rgba(255, 255, 255, 0.05)',
    cardShadow: '0 10px 40px -10px rgba(0,0,0,0.5)',
  },
  minimal: {
    id: 'minimal',
    name: 'Minimal Clean',
    layout: 'stacked',
    buttonStyle: 'rounded',
    fontStyle: 'modern',
    background: '#ffffff',
    textColor: '#1a1a1a',
    accentColor: '#000000',
    cardBg: '#f3f4f6',
  },
  neon: {
    id: 'neon',
    name: 'Dark Neon',
    layout: 'stacked',
    buttonStyle: 'hard-shadow',
    fontStyle: 'mono',
    background: '#0f172a',
    textColor: '#ffffff',
    accentColor: '#22d3ee',
    cardBg: '#1e293b',
    cardBorder: '1px solid #22d3ee',
    cardShadow: '0 0 10px #22d3ee',
  },
  gradient: {
    id: 'gradient',
    name: 'Soft Gradient',
    layout: 'stacked',
    buttonStyle: 'pill',
    fontStyle: 'modern',
    background: 'linear-gradient(135deg, #fdfbfb 0%, #ebedee 100%)',
    textColor: '#4a5568',
    accentColor: '#ec4899',
    cardBg: 'rgba(255, 255, 255, 0.8)',
    cardShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
  },
  glass: {
    id: 'glass',
    name: 'Glass Card',
    layout: 'stacked',
    buttonStyle: 'rounded',
    fontStyle: 'modern',
    background: 'linear-gradient(to right, #4facfe 0%, #00f2fe 100%)',
    textColor: '#ffffff',
    accentColor: '#ffffff',
    cardBg: 'rgba(255, 255, 255, 0.2)',
    cardBorder: '1px solid rgba(255, 255, 255, 0.3)',
    cardShadow: '0 8px 32px 0 rgba(31, 38, 135, 0.37)',
  },
  bold: {
    id: 'bold',
    name: 'Bold Creator',
    layout: 'grid',
    buttonStyle: 'square',
    fontStyle: 'serif',
    background: '#fbbf24',
    textColor: '#000000',
    accentColor: '#000000',
    cardBg: '#ffffff',
    cardBorder: '2px solid #000000',
    cardShadow: '4px 4px 0px #000000',
  },
  sunset: {
    id: 'sunset',
    name: 'Sunset Vibes',
    layout: 'stacked',
    buttonStyle: 'pill',
    fontStyle: 'modern',
    background: 'linear-gradient(-45deg, #ff9a9e, #fad0c4, #ffd1ff, #a18cd1)',
    bgSize: '400% 400%',
    animation: 'gradient 15s ease infinite',
    textColor: '#ffffff',
    accentColor: '#ff9a9e',
    cardBg: 'rgba(255, 255, 255, 0.25)',
    cardShadow: '0 8px 32px 0 rgba(31, 38, 135, 0.15)',
    cardBorder: '1px solid rgba(255, 255, 255, 0.18)',
  },
  ocean: {
    id: 'ocean',
    name: 'Deep Ocean',
    layout: 'stacked',
    buttonStyle: 'rounded',
    fontStyle: 'modern',
    background: 'linear-gradient(-45deg, #2193b0, #6dd5ed, #2980b9, #6dd5ed)',
    bgSize: '400% 400%',
    animation: 'gradient 15s ease infinite',
    textColor: '#ffffff',
    accentColor: '#2193b0',
    cardBg: 'rgba(255, 255, 255, 0.15)',
    cardBorder: '1px solid rgba(255, 255, 255, 0.2)',
  },
  forest: {
    id: 'forest',
    name: 'Mystic Forest',
    layout: 'grid',
    buttonStyle: 'rounded',
    fontStyle: 'serif',
    background: 'linear-gradient(-45deg, #134e5e, #71b280, #2c3e50, #000000)',
    bgSize: '400% 400%',
    animation: 'gradient 20s ease infinite',
    textColor: '#e2e8f0',
    accentColor: '#71b280',
    cardBg: 'rgba(0, 0, 0, 0.4)',
    cardBorder: '1px solid rgba(113, 178, 128, 0.3)',
  },
  midnight: {
    id: 'midnight',
    name: 'Midnight Dream',
    layout: 'stacked',
    buttonStyle: 'pill',
    fontStyle: 'modern',
    background: 'linear-gradient(-45deg, #232526, #414345, #000000, #2c3e50)',
    bgSize: '400% 400%',
    animation: 'gradient 15s ease infinite',
    textColor: '#ffffff',
    accentColor: '#6366f1',
    cardBg: 'rgba(255, 255, 255, 0.05)',
    cardBorder: '1px solid rgba(255, 255, 255, 0.1)',
  },
  cyber: {
    id: 'cyber',
    name: 'Cyber Punk',
    layout: 'grid',
    buttonStyle: 'hard-shadow',
    fontStyle: 'mono',
    background: 'linear-gradient(-45deg, #fce38a, #f38181, #00cdac, #000000)',
    bgSize: '400% 400%',
    animation: 'gradient-xy 10s ease infinite',
    textColor: '#000000',
    accentColor: '#f38181',
    cardBg: '#ffffff',
    cardShadow: '4px 4px 0px #000000',
  },
  retro: {
    id: 'retro',
    name: 'Retro Wave',
    layout: 'stacked',
    buttonStyle: 'rounded',
    fontStyle: 'modern',
    background: 'linear-gradient(to bottom, #3a1c71, #d76d77, #ffaf7b)',
    bgSize: '100% 400%',
    animation: 'gradient-y 10s ease infinite',
    textColor: '#ffffff',
    accentColor: '#ffaf7b',
    cardBg: 'rgba(0, 0, 0, 0.3)',
    cardBorder: '1px solid rgba(255, 175, 123, 0.5)',
  },
  pastel: {
    id: 'pastel',
    name: 'Pastel Dream',
    layout: 'stacked',
    buttonStyle: 'pill',
    fontStyle: 'modern',
    background: 'linear-gradient(-45deg, #ff9a9e, #fecfef, #feada6, #f5efef)',
    bgSize: '400% 400%',
    animation: 'gradient 12s ease infinite',
    textColor: '#5d5d5d',
    accentColor: '#ff9a9e',
    cardBg: 'rgba(255, 255, 255, 0.7)',
    cardShadow: '0 4px 15px rgba(0,0,0,0.05)',
  },
  monochrome: {
    id: 'monochrome',
    name: 'Mono Motion',
    layout: 'stacked',
    buttonStyle: 'square',
    fontStyle: 'modern',
    background: 'linear-gradient(-45deg, #000000, #434343, #000000, #2c3e50)',
    bgSize: '400% 400%',
    animation: 'gradient 20s ease infinite',
    textColor: '#ffffff',
    accentColor: '#ffffff',
    cardBg: 'transparent',
    cardBorder: '1px solid #ffffff',
  },
  galaxy: {
    id: 'galaxy',
    name: 'Galaxy',
    layout: 'grid',
    buttonStyle: 'rounded',
    fontStyle: 'modern',
    background: 'linear-gradient(-45deg, #0f2027, #203a43, #2c5364, #4b0082)',
    bgSize: '400% 400%',
    animation: 'gradient 15s ease infinite',
    textColor: '#e0e0e0',
    accentColor: '#00d2ff',
    cardBg: 'rgba(255, 255, 255, 0.1)',
    cardShadow: '0 0 20px rgba(0, 210, 255, 0.2)',
  },
  aurora: {
    id: 'aurora',
    name: 'Aurora Borealis',
    layout: 'stacked',
    buttonStyle: 'pill',
    fontStyle: 'modern',
    background: 'linear-gradient(-45deg, #00c6ff, #0072ff, #00c6ff, #1aff00)',
    bgSize: '400% 400%',
    animation: 'gradient 10s ease infinite',
    textColor: '#ffffff',
    accentColor: '#1aff00',
    cardBg: 'rgba(0, 0, 0, 0.2)',
    cardBorder: '1px solid rgba(255, 255, 255, 0.2)',
  },
  volcano: {
    id: 'volcano',
    name: 'Volcanic Ash',
    layout: 'stacked',
    buttonStyle: 'hard-shadow',
    fontStyle: 'modern',
    background: 'linear-gradient(-45deg, #cb2d3e, #ef473a, #ff6b6b, #2c3e50)',
    bgSize: '400% 400%',
    animation: 'gradient 8s ease infinite',
    textColor: '#ffffff',
    accentColor: '#ff6b6b',
    cardBg: '#1a1a1a',
    cardBorder: '1px solid #ef473a',
  },
  glacier: {
    id: 'glacier',
    name: 'Glacier Ice',
    layout: 'stacked',
    buttonStyle: 'rounded',
    fontStyle: 'modern',
    background: 'linear-gradient(to bottom, #e6e9f0 0%, #eef1f5 100%)',
    bgSize: '100% 100%',
    animation: 'pulse-slow 5s ease-in-out infinite',
    textColor: '#5f6c7b',
    accentColor: '#3b82f6',
    cardBg: 'rgba(255, 255, 255, 0.9)',
    cardShadow: '0 10px 25px rgba(59, 130, 246, 0.1)',
  },
  desert: {
    id: 'desert',
    name: 'Desert Sands',
    layout: 'stacked',
    buttonStyle: 'rounded',
    fontStyle: 'serif',
    background: 'linear-gradient(-45deg, #C9D6FF, #E2E2E2, #F4A460, #D2691E)',
    bgSize: '400% 400%',
    animation: 'gradient 20s ease infinite',
    textColor: '#4a3b32',
    accentColor: '#D2691E',
    cardBg: 'rgba(255, 255, 255, 0.6)',
    cardBorder: '1px solid rgba(210, 105, 30, 0.2)',
  },
  jungle: {
    id: 'jungle',
    name: 'Deep Jungle',
    layout: 'grid',
    buttonStyle: 'rounded',
    fontStyle: 'modern',
    background: 'linear-gradient(-45deg, #11998e, #38ef7d, #0f9b0f, #000000)',
    bgSize: '400% 400%',
    animation: 'gradient 15s ease infinite',
    textColor: '#ffffff',
    accentColor: '#38ef7d',
    cardBg: 'rgba(0, 0, 0, 0.5)',
    cardBorder: '1px solid rgba(56, 239, 125, 0.3)',
  },
  candy: {
    id: 'candy',
    name: 'Cotton Candy',
    layout: 'stacked',
    buttonStyle: 'pill',
    fontStyle: 'modern',
    background: 'linear-gradient(-45deg, #ff9a9e, #fad0c4, #fad0c4, #ffd1ff)',
    bgSize: '400% 400%',
    animation: 'gradient-xy 8s ease infinite',
    textColor: '#6b4c4c',
    accentColor: '#ff9a9e',
    cardBg: 'rgba(255, 255, 255, 0.8)',
    cardShadow: '0 4px 15px rgba(255, 154, 158, 0.3)',
  },
  royal: {
    id: 'royal',
    name: 'Royal Purple',
    layout: 'stacked',
    buttonStyle: 'rounded',
    fontStyle: 'serif',
    background: 'linear-gradient(-45deg, #141E30, #243B55, #4b0082, #800080)',
    bgSize: '400% 400%',
    animation: 'gradient 15s ease infinite',
    textColor: '#ffd700',
    accentColor: '#ffd700',
    cardBg: 'rgba(20, 30, 48, 0.8)',
    cardBorder: '1px solid rgba(255, 215, 0, 0.3)',
  },
  slate: {
    id: 'slate',
    name: 'Clean Slate',
    layout: 'stacked',
    buttonStyle: 'square',
    fontStyle: 'modern',
    background: 'linear-gradient(-45deg, #2c3e50, #bdc3c7, #2c3e50, #34495e)',
    bgSize: '400% 400%',
    animation: 'gradient 20s ease infinite',
    textColor: '#ffffff',
    accentColor: '#bdc3c7',
    cardBg: 'rgba(255, 255, 255, 0.1)',
    cardBorder: '1px solid rgba(255, 255, 255, 0.1)',
  },
  coffee: {
    id: 'coffee',
    name: 'Morning Coffee',
    layout: 'stacked',
    buttonStyle: 'rounded',
    fontStyle: 'serif',
    background: 'linear-gradient(-45deg, #3e2b26, #5d4037, #795548, #8d6e63)',
    bgSize: '400% 400%',
    animation: 'gradient 18s ease infinite',
    textColor: '#efebe9',
    accentColor: '#d7ccc8',
    cardBg: 'rgba(62, 43, 38, 0.6)',
    cardBorder: '1px solid rgba(141, 110, 99, 0.3)',
  },
  lavender: {
    id: 'lavender',
    name: 'Lavender Mist',
    layout: 'stacked',
    buttonStyle: 'pill',
    fontStyle: 'modern',
    background: 'linear-gradient(-45deg, #E6E6FA, #D8BFD8, #DDA0DD, #EE82EE)',
    bgSize: '400% 400%',
    animation: 'gradient 12s ease infinite',
    textColor: '#4b0082',
    accentColor: '#8a2be2',
    cardBg: 'rgba(255, 255, 255, 0.6)',
    cardShadow: '0 4px 10px rgba(138, 43, 226, 0.1)',
  },
  mint: {
    id: 'mint',
    name: 'Fresh Mint',
    layout: 'stacked',
    buttonStyle: 'rounded',
    fontStyle: 'modern',
    background: 'linear-gradient(-45deg, #00b09b, #96c93d, #00b09b, #43cea2)',
    bgSize: '400% 400%',
    animation: 'gradient 15s ease infinite',
    textColor: '#ffffff',
    accentColor: '#ffffff',
    cardBg: 'rgba(255, 255, 255, 0.2)',
    cardBorder: '1px solid rgba(255, 255, 255, 0.4)',
  },
  creator_black_pro: {
    id: 'creator_black_pro',
    name: 'Creator Black Pro',
    layout: 'stacked',
    buttonStyle: 'pill', // Will override radius in renderer
    fontStyle: 'modern',
    background: '#0B0B0E',
    textColor: '#FFFFFF',
    accentColor: '#FFFFFF',
    cardBg: '#1A1A1F',
    cardBorder: '1px solid rgba(255, 255, 255, 0.05)',
    cardShadow: '0 2px 10px rgba(0, 0, 0, 0.2)',
  },
  sunset_gradient_pro: {
    id: 'sunset_gradient_pro',
    name: 'Sunset Gradient Pro',
    layout: 'stacked',
    buttonStyle: 'rounded', // Will override radius to 20px in renderer
    fontStyle: 'modern',
    background: 'linear-gradient(180deg, #D0E1F9 0%, #E6E6FA 45%, #FFB7B2 100%)',
    textColor: '#2D3748',
    accentColor: '#4A5568',
    cardBg: '#FFFFFF',
    cardShadow: '0 4px 20px rgba(0, 0, 0, 0.08)',
    textOpacity: 0.9,
  },
  editorial_luxe: {
    id: 'editorial_luxe',
    name: 'Editorial Luxe',
    layout: 'stacked',
    buttonStyle: 'rounded',
    fontStyle: 'serif',
    background: '#F3EFE9',
    textColor: '#1A1A1A',
    accentColor: '#1A1A1A',
    cardBg: 'transparent',
    cardBorder: '1.5px solid #1A1A1A',
    textOpacity: 1,
  },
  glass_elite: {
    id: 'glass_elite',
    name: 'Glass Elite',
    layout: 'stacked',
    buttonStyle: 'rounded',
    fontStyle: 'modern',
    background: '#0F172A', // Slate 900 base
    textColor: '#FFFFFF',
    accentColor: '#818CF8',
    cardBg: 'rgba(255, 255, 255, 0.03)',
    cardBorder: '1px solid rgba(255, 255, 255, 0.08)',
    cardShadow: '0 8px 32px 0 rgba(0, 0, 0, 0.3)',
    cardBackdropBlur: 'blur(16px)',
    blobAnimation: true,
  },
  classic_solid_pro: {
    id: 'classic_solid_pro',
    name: 'Classic Solid Pro',
    layout: 'stacked',
    buttonStyle: 'rounded',
    fontStyle: 'modern',
    background: '#39E09B', // Classic Linktree Green
    textColor: '#000000',
    accentColor: '#000000',
    cardBg: '#FFFFFF',
    cardShadow: '0 2px 4px rgba(0,0,0,0.08)',
    textOpacity: 1,
  },
  clean_light_pro: {
    id: 'clean_light_pro',
    name: 'Clean Light Pro',
    layout: 'stacked',
    buttonStyle: 'rounded', // Will override radius to 14px in renderer
    fontStyle: 'modern',
    background: '#FFFFFF',
    textColor: '#000000',
    accentColor: '#000000',
    cardBg: '#000000',
    cardShadow: '0 4px 12px rgba(0, 0, 0, 0.08)', // Subtle shadow
    textOpacity: 1,
  },
  soft_dark_pro: {
    id: 'soft_dark_pro',
    name: 'Soft Dark Pro',
    layout: 'stacked',
    buttonStyle: 'rounded', // Will override radius to 14px in renderer
    fontStyle: 'modern',
    background: '#121214',
    textColor: '#FFFFFF',
    accentColor: '#FFFFFF',
    cardBg: '#1C1C22',
    textOpacity: 1,
  },
  solid_light_core: {
    id: 'solid_light_core',
    name: 'Solid Light Core',
    layout: 'stacked',
    buttonStyle: 'rounded', // Will override radius to 14px in renderer
    fontStyle: 'modern',
    background: '#FFFFFF',
    textColor: '#000000',
    accentColor: '#000000',
    cardBg: '#000000',
    textOpacity: 1,
  },
  accent_solid_minimal: {
    id: 'accent_solid_minimal',
    name: 'Accent Solid Minimal',
    layout: 'stacked',
    buttonStyle: 'rounded', // Will override radius to 14px in renderer
    fontStyle: 'modern',
    background: '#4F46E5', // Default accent color (Indigo 600)
    textColor: '#FFFFFF',
    accentColor: '#FFFFFF',
    cardBg: '#FFFFFF',
    cardShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
    textOpacity: 1,
  },
  '3d_elevation_stack': {
    id: '3d_elevation_stack',
    name: '3D Elevation Stack',
    layout: 'stacked',
    buttonStyle: 'rounded', // Will override radius to 16px in renderer
    fontStyle: 'modern',
    background: '#101014',
    textColor: '#FFFFFF',
    accentColor: '#FFFFFF',
    cardBg: '#1C1C22',
    cardShadow: '0 4px 10px rgba(0,0,0,0.3), inset 0 1px 0 rgba(255,255,255,0.05)', // Base shadow
    textOpacity: 1,
  },
  'floating_panels_pro': {
    id: 'floating_panels_pro',
    name: 'Floating Panels Pro',
    layout: 'stacked',
    buttonStyle: 'rounded', // Will override radius to 18px in renderer
    fontStyle: 'modern',
    background: '#0F172A', // Midnight Blue
    textColor: '#FFFFFF',
    accentColor: '#38BDF8', // Light blue accent
    cardBg: '#1E293B', // Slate 800
    cardShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.3), 0 4px 6px -2px rgba(0, 0, 0, 0.1), inset 0 1px 0 rgba(255, 255, 255, 0.1)', // Layered shadow + top highlight
    textOpacity: 1,
  },
  'royal_ember_3d': {
    id: 'royal_ember_3d',
    name: 'Royal Ember 3D',
    layout: 'stacked',
    buttonStyle: 'rounded', // Will override radius to 18px in renderer
    fontStyle: 'modern',
    background: '#2B0F54', // Solid deep royal purple
    textColor: '#FFFFFF',
    accentColor: '#FF7A18', // Orange accent
    cardBg: '#3A136A', // Rich purple
    cardBorder: '2px solid #FF7A18',
    cardShadow: '0 10px 20px -5px rgba(43, 15, 84, 0.8), 0 0 15px rgba(255, 122, 24, 0.15)', // Deep purple shadow + soft orange glow
    textOpacity: 1,
  },
  ember_contrast_pro: {
    id: 'ember_contrast_pro',
    name: 'Ember Contrast Pro',
    layout: 'stacked',
    buttonStyle: 'rounded',
    fontStyle: 'modern',
    background: '#F97316', // Solid vibrant orange
    textColor: '#FFFFFF',
    accentColor: '#3B0764', // Deep purple
    cardBg: '#3B0764', // Deep purple buttons
    cardShadow: '0 10px 20px -5px rgba(59, 7, 100, 0.5)',
    textOpacity: 1,
  },
  ultra_depth_purple: {
    id: 'ultra_depth_purple',
    name: 'Ultra Depth Purple Core',
    layout: 'stacked',
    buttonStyle: 'rounded',
    fontStyle: 'modern',
    background: '#240046', // Solid dark violet
    textColor: '#FFFFFF',
    accentColor: '#FF9100', // Orange accent
    cardBg: '#3C096C', // Lighter purple
    cardShadow: '0 10px 20px rgba(0,0,0,0.4), inset 0 1px 0 rgba(255,255,255,0.1)',
    textOpacity: 1,
  },
  elegant_portrait_card: {
    id: 'elegant_portrait_card',
    name: 'Elegant Portrait Card',
    layout: 'profile-card',
    buttonStyle: 'circular',
    fontStyle: 'serif',
    background: '#B88986', // Solid dusty rose
    textColor: '#8E4F4B', // Darker rose for text/icons
    accentColor: '#F3E8E4', // Light beige
    cardBg: '#F3E8E4', // Light beige for buttons
    cardShadow: '0 4px 12px rgba(0, 0, 0, 0.05)',
    
    // Template Engine Rules
    templateName: 'Elegant Portrait Card',
    layoutType: 'profile-card',
    maxButtons: 2,
    minButtons: 2,
    allowIcons: true,
    allowImages: false,
    allowSections: false,
    animationStyle: 'soft-micro',
    layoutLocked: true,
    buttonSlots: [
      { id: 'primaryAction', position: 1, label: 'Primary Action', defaultIcon: 'instagram' },
      { id: 'secondaryAction', position: 2, label: 'Secondary Action', defaultIcon: 'message-circle' }
    ]
  },
  neon_pulse_profile: {
    id: 'neon_pulse_profile',
    name: 'Neon Pulse Profile',
    layout: 'stacked',
    buttonStyle: 'pill',
    fontStyle: 'modern',
    background: 'linear-gradient(135deg, #5B2EFF 0%, #8A5CFF 50%, #FF8A2A 100%)',
    textColor: '#1F1F1F',
    accentColor: '#FF8A2A',
    cardBg: 'rgba(255, 255, 255, 0.85)',
    cardBorder: '1px solid rgba(255, 255, 255, 0.4)',
    cardShadow: '0 20px 40px rgba(0, 0, 0, 0.1)',
    cardBackdropBlur: 'blur(20px)',
    animation: 'gradient-diagonal 15s ease infinite',
    bgSize: '400% 400%',
    
    // Template Engine Rules
    templateName: 'Neon Pulse Profile',
    layoutType: 'stacked',
    maxButtons: 10,
    minButtons: 1,
    allowIcons: false,
    allowImages: false,
    allowSections: false,
    animationStyle: 'flutter-stagger',
    layoutLocked: true,
  },
};
